package core;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Arrays;
import models.Song;

/**
 *
 * @author andre
 */
public class LoggedDetailedSong extends javax.swing.JFrame {

    public String id;
    Utilities utilities = new Utilities();
    
    /**
     * Creates new form LoggedDetailedSong
     */
    public LoggedDetailedSong(String id) {
        this.id = id;
        
        initComponents();
        
        Song song = utilities.getSongsById(id);
        
        detailedsong_id.setText(song.getId());
        detailedsong_title.setText(song.getTitle());
        detailedsong_author.setText(song.getAuthor());
        detailedsong_year.setText(song.getYear());
        
        ArrayList<float[]> results = utilities.visualizzaEmozioneBrano(id);
        Font font = new Font("Segou UI", Font.ITALIC, 16);
        
        if (results.get(0)[0] == 0.0) {
            detailedsong_rabbia.setFont(font);
            detailedsong_rabbia.setText("Questa emozione non è stata ancora provata da nessun utente.");
        } else {
            detailedsong_rabbia.setText("Questa emozione è stata provata da " + Math.round(results.get(0)[0]) + " utenti ed ha totalizzato una media di intensità di " + results.get(0)[1] + ".");
        }
        
        if (results.get(1)[0] == 0.0) {
            detailedsong_paura.setFont(font);
            detailedsong_paura.setText("Questa emozione non è stata ancora provata da nessun utente.");
        } else {
            detailedsong_paura.setText("Questa emozione è stata provata da " + Math.round(results.get(1)[0]) + " utenti ed ha totalizzato una media di intensità di " + results.get(1)[1] + ".");
        }
        
        if (results.get(2)[0] == 0.0) {
            detailedsong_felicita.setFont(font);
            detailedsong_felicita.setText("Questa emozione non è stata ancora provata da nessun utente.");
        } else {
            detailedsong_felicita.setText("Questa emozione è stata provata da " + Math.round(results.get(2)[0]) + " utenti ed ha totalizzato una media di intensità di " + results.get(2)[1] + ".");
        }
        
        if (results.get(3)[0] == 0.0) {
            detailedsong_nostalgia.setFont(font);
            detailedsong_nostalgia.setText("Questa emozione non è stata ancora provata da nessun utente.");
        } else {
            detailedsong_nostalgia.setText("Questa emozione è stata provata da " + Math.round(results.get(3)[0]) + " utenti ed ha totalizzato una media di intensità di " + results.get(3)[1] + ".");
        }
        
        if (results.get(4)[0] == 0.0) {
            detailedsong_tristezza.setFont(font);
            detailedsong_tristezza.setText("Questa emozione non è stata ancora provata da nessun utente.");
        } else {
            detailedsong_tristezza.setText("Questa emozione è stata provata da " + Math.round(results.get(4)[0]) + " utenti ed ha totalizzato una media di intensità di " + results.get(4)[1] + ".");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        detailedsong_id = new javax.swing.JLabel();
        detailedsong_title = new javax.swing.JLabel();
        detailedsong_author = new javax.swing.JLabel();
        detailedsong_year = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        detailedsong_rabbia = new javax.swing.JLabel();
        detailedsong_paura = new javax.swing.JLabel();
        detailedsong_felicita = new javax.swing.JLabel();
        detailedsong_nostalgia = new javax.swing.JLabel();
        detailedsong_tristezza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Canzone selezionata:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setText("Titolo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Autore:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setText("Anno:");

        jButton1.setText("Indietro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        detailedsong_id.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_id.setText("id");

        detailedsong_title.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_title.setText("titolo");

        detailedsong_author.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_author.setText("autore");

        detailedsong_year.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_year.setText("anno");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Riassunto emozioni:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setText("Rabbia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel8.setText("Paura:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Felicità:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel10.setText("Nostalgia:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel11.setText("Tristezza:");

        detailedsong_rabbia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_rabbia.setText("rabbia");

        detailedsong_paura.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_paura.setText("paura");

        detailedsong_felicita.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_felicita.setText("felicità");

        detailedsong_nostalgia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_nostalgia.setText("nostalgia");

        detailedsong_tristezza.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailedsong_tristezza.setText("tristezza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailedsong_year)
                                    .addComponent(detailedsong_id)
                                    .addComponent(detailedsong_title)
                                    .addComponent(detailedsong_author)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailedsong_tristezza)
                                    .addComponent(detailedsong_nostalgia)
                                    .addComponent(detailedsong_felicita)
                                    .addComponent(detailedsong_paura)
                                    .addComponent(detailedsong_rabbia))))
                        .addGap(0, 573, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(detailedsong_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(detailedsong_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(detailedsong_author))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(detailedsong_year))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(detailedsong_rabbia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(detailedsong_paura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(detailedsong_felicita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(detailedsong_nostalgia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(detailedsong_tristezza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        EmotionalSongs emotionalSongs = new EmotionalSongs();
        emotionalSongs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedDetailedSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedDetailedSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedDetailedSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedDetailedSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedDetailedSong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailedsong_author;
    private javax.swing.JLabel detailedsong_felicita;
    private javax.swing.JLabel detailedsong_id;
    private javax.swing.JLabel detailedsong_nostalgia;
    private javax.swing.JLabel detailedsong_paura;
    private javax.swing.JLabel detailedsong_rabbia;
    private javax.swing.JLabel detailedsong_title;
    private javax.swing.JLabel detailedsong_tristezza;
    private javax.swing.JLabel detailedsong_year;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

